name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: go in to sub dir
        working-directory: goapp
        run: go get api
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
          basePath: goapp
